### ISSUE TITLE
レビュー依頼

### ISSUE THREAD

**Issue by ni3520** [ni3520/original#11]

**Comment by ni3520** [comment]
■Webアプリの概要
継続を記録するアプリ
取組課題を決め、できたらカレンダーにチェックしてく。３段階のレベルを設定し、達成できたレベルに応じて、カレンダーが濃さの違う緑色に変化していく

■1週間辺りの開発に向けられる時間
- 1週間あたり：25時間

■ProjectsのURL
https://github.com/users/ni3520/projects/1/views/1?sumFields=%5B146588548%5D&hideItemsCount=false

■MVPリリースまで

- [ ] 会員登録
- [ ] ログイン機能
- [ ] 取組一覧
- [ ] 取組ページ
- [ ] 取組ページカレンダー機能
- [ ] 記録ページ

■MVP後

- [ ] 通知機能

**Comment by rdhdchloe** [comment]
概ね良いかと思います。LGTMです。
